AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  KeyPair:
    Description: Select KeyPair Name.
    Type: AWS::EC2::KeyPair::KeyName
  DBUser:
    Type: String
  DBPassword:
    Type: String
Resources:
  vpc0c0e654fda8ca9956:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      InstanceTenancy: default
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'false'
      Tags:
        - Key: Name
          Value: adc-library-vpc
  subnet020ccd3cae611f485:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref 'vpc0c0e654fda8ca9956'
      Tags:
        - Key: Name
          Value: adc-library-private-subnet-1a
  subnet0562fa81fc7deced8:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref 'vpc0c0e654fda8ca9956'
      Tags:
        - Key: Name
          Value: adc-library-public-subnet-1a
  subnet08778bd45fe06c222:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: ap-northeast-1c
      VpcId: !Ref 'vpc0c0e654fda8ca9956'
      Tags:
        - Key: Name
          Value: adc-library-private-subnet-1c
  igw0bd4226e0773184b9:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: adc-library-igw
  acl095774f3b3f36fb4a:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref 'vpc0c0e654fda8ca9956'
  rtb05e7a356f6d366da6:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref 'vpc0c0e654fda8ca9956'
      Tags:
        - Key: Name
          Value: adc-library-public-rt
  rtb65970103:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: vpc-4a625b2d
  eip542500181:
    Type: AWS::EC2::EIP
    DependsOn:
      - gw1
    Properties:
      Domain: vpc
  instancei0cd139b02054fa64b:
    Type: AWS::EC2::Instance
    Properties:
      DisableApiTermination: 'false'
      InstanceInitiatedShutdownBehavior: stop
      ImageId: ami-068a6cefc24c301d2
      InstanceType: t2.micro
      KeyName:
        Ref: KeyPair
      Monitoring: 'false'
      Tags:
        - Key: Name
          Value: Web-1a
      NetworkInterfaces:
        - DeleteOnTermination: 'true'
          Description: Primary network interface
          DeviceIndex: 0
          SubnetId: !Ref 'subnet0562fa81fc7deced8'
          PrivateIpAddresses:
            - PrivateIpAddress: 10.0.1.158
              Primary: 'true'
          GroupSet:
            - !Ref 'sglaunchwizard1'
  rdslibrary:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '20'
      AllowMajorVersionUpgrade: 'false'
      AutoMinorVersionUpgrade: 'true'
      DBInstanceClass: db.t2.micro
      Port: '5432'
      StorageType: gp2
      BackupRetentionPeriod: '7'
      MasterUserPassword:
        Ref: DBPassword
      MasterUsername:
        Ref: DBUser
      PreferredBackupWindow: 19:36-20:06
      PreferredMaintenanceWindow: tue:15:00-tue:15:30
      DBName: MyDatabase
      Engine: postgres
      EngineVersion: '11.5'
      LicenseModel: postgresql-license
      DBSubnetGroupName: !Ref 'dbsubnetdefaultvpc0c0e654fda8ca9956'
      VPCSecurityGroups:
        - !Ref 'sgdbsg'
  dbsubnetdefaultvpc0c0e654fda8ca9956:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Created from the RDS Management Console
      SubnetIds:
        - !Ref 'subnet08778bd45fe06c222'
        - !Ref 'subnet0562fa81fc7deced8'
        - !Ref 'subnet020ccd3cae611f485'
  sglaunchwizard1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: launch-wizard-1 created 2019-11-23T14:22:35.651+09:00
      VpcId: !Ref 'vpc0c0e654fda8ca9956'
      Tags:
        - Key: Name
          Value: web-sg
  sgdbsg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Created by RDS management console
      VpcId: !Ref 'vpc0c0e654fda8ca9956'
      Tags:
        - Key: Name
          Value: db-sg
  dbsgdefault:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      GroupDescription: default
  acl1:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: 'true'
      Protocol: '-1'
      RuleAction: allow
      RuleNumber: '100'
      NetworkAclId: !Ref 'acl095774f3b3f36fb4a'
  acl2:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Protocol: '-1'
      RuleAction: allow
      RuleNumber: '100'
      NetworkAclId: !Ref 'acl095774f3b3f36fb4a'
  subnetacl1:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref 'acl095774f3b3f36fb4a'
      SubnetId: !Ref 'subnet020ccd3cae611f485'
  subnetacl2:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref 'acl095774f3b3f36fb4a'
      SubnetId: !Ref 'subnet0562fa81fc7deced8'
  subnetacl3:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref 'acl095774f3b3f36fb4a'
      SubnetId: !Ref 'subnet08778bd45fe06c222'
  gw1:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref 'vpc0c0e654fda8ca9956'
      InternetGatewayId: !Ref 'igw0bd4226e0773184b9'
  subnetroute1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref 'rtb05e7a356f6d366da6'
      SubnetId: !Ref 'subnet0562fa81fc7deced8'
  route1:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref 'rtb05e7a356f6d366da6'
      GatewayId: !Ref 'igw0bd4226e0773184b9'
    DependsOn: gw1
  route2:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref 'rtb65970103'
      GatewayId: igw-50dbde34
  dchpassoc1:
    Type: AWS::EC2::VPCDHCPOptionsAssociation
    Properties:
      VpcId: !Ref 'vpc0c0e654fda8ca9956'
      DhcpOptionsId: dopt-74517613
  assoc1:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt 'eip542500181.AllocationId'
      InstanceId: !Ref 'instancei0cd139b02054fa64b'
  ingress1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref 'sglaunchwizard1'
      IpProtocol: tcp
      FromPort: '8080'
      ToPort: '8080'
      CidrIp: 0.0.0.0/0
  ingress2:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref 'sglaunchwizard1'
      IpProtocol: tcp
      FromPort: '22'
      ToPort: '22'
      CidrIp: 0.0.0.0/0
  ingress3:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref 'sgdbsg'
      IpProtocol: tcp
      FromPort: '5432'
      ToPort: '5432'
      SourceSecurityGroupId: !Ref 'sglaunchwizard1'
      SourceSecurityGroupOwnerId: '555965179337'
  egress1:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref 'sglaunchwizard1'
      IpProtocol: '-1'
      CidrIp: 0.0.0.0/0
  egress2:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref 'sgdbsg'
      IpProtocol: '-1'
      CidrIp: 0.0.0.0/0
Description: library
