spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/library
    username: libuser
    password: libpass
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /api
