spring:
  datasource:
    url: ${DATABASE_URL_SPRINGBOOT:jdbc:postgresql://localhost:15432/library}
    username: ${DATABASE_USER:libuser}
    password: ${DATABASE_PASS:libpass}
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /api
