openapi: 3.0.0
info:
  title: libraryApplication
  version: 1.0.0
  description: '図書館アプリのライブラリ'
servers:
  - url: 'http://localhost:8080/api/v1'
    description: local Server
  - url: 'https://enigmatic-depths-14464.herokuapp.com/api/v1'
    description: Main Server
paths:
  /books:
    $ref: './paths/books.yaml#/books'
  '/books/inventory/{version}':
    $ref: './paths/booksInventory.yaml#/inventory'
  '/books/inventory/{version}/{isbn}':
    $ref: './paths/booksInventory.yaml#/inventoryEvent'
  '/books/{isbn}':
    $ref: './paths/books.yaml#/isbn'
  '/lendingRecords':
    $ref: './paths/lendingRecords.yaml#/root'
  '/ranking/books':
    $ref: './paths/ranking.yaml#/books'
  '/users':
    $ref: './paths/users.yaml#/all'
  '/users/{userId}':
    $ref: './paths/users.yaml#/id'

