name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.5
    - name: sudo
      run: sudo chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: test
      run: ./gradlew test
    - name: sonarcloud
      run: ./gradlew sonarqube
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_SONAR }}
  FrontDeploy:
    name: FrontDeploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependencies
        run: npm install
        working-directory: ./library-frontend-service
      - name: Build
        working-directory: ./library-frontend-service
        run: npm run build
      - name: deploy to Firebase Hosting
        working-directory: ./library-frontend-service
        run: |
          ./node_modules/.bin/firebase deploy --token=${{ secrets.FIREBASE_TOKEN }}

  frontCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: yarn install
        run:  sudo apt-get update && sudo apt-get install yarn
      - name: package install
        run:  yarn
      - name: lint
        run:  yarn lint:output
      - name: test
        run:  yarn test:unit:cov
      - name: SonarCloudScan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.GITHUB_FRONT_SONAR }}